### ISSUE TITLE
Delete from Variable does not work correctly if there is a index created for associated Vertex

### ISSUE THREAD

**Issue by mindnuts** [orientechnologies/orientjs#194] opened 2016-08-03 15:10 UTC
Hi...i have an issue where delete from variables is not working correctly inside a LET block if there is an associated index.

Envrionment info:
Orientdb 2.1.x
Orientjs  2.1.11 and 2.2.1

To reproduce the bug create a new database and execute the commands from studio:
```sql
CREATE VERTEX Addresses extends V
CREATE PROPERTY Addresses.city STRING
CREATE PROPERTY Addresses.id STRING
CREATE PROPERTY Addresses.street STRING

CREATE VERTEX Employees extends V
CREATE PROPERTY Employees.email STRING
CREATE PROPERTY Employees.name STRING
CREATE PROPERTY Employees.id STRING


INSERT INTO Employees SET name = 'Homer Simpson', email = 'homer@nuclear.com', id = "818bd3cf-6dd4-407b-8290-5f4b4525a5a6"

INSERT INTO Addresses SET city = 'Springfield', street = '54, down lane', id = "80007b02-ca18-4629-af8e-a3ef5a1702f4"
INSERT INTO Addresses SET city = 'rohbach', street = '34, nashbrough', id = "4fee1921-be40-4a8c-be6c-fedf826e414f"

#create edge from Addresses to Employees assuming Vertex Addresses cluster id is 15

CREATE EDGE belongs_to extends E
create edge belongs_to from #15:0 to #12:1
create edge belongs_to from #15:1 to #12:1

#fetch all Addresses for employee with email id homer@nuclear.com
select list(id) from (select expand (in('belongs_to'))  from Employees where email = 'homer@nuclear.com' )
```

Test.js
```js
'use strict';
var OrientDB = require('orientjs');
var server = OrientDB({
  host: '172.17.8.101',
  port: 2424,
  username: 'root',
  password: 'root'
});

var db = server.use('Testing');

db
  .let('appIds', "select list(id) from (select expand (in('belongs_to')) \
     from Employees where email = 'homer@nuclear.com' )")
  .let('appId', "delete vertex Addresses where  id in $appIds")
  .let('candId',"delete vertex Employees where  email = 'homer@nuclear.com' ") //delete from Employee
  .commit()
  .return('$appIds')
  .one()
  .then(function(rec) {
      console.log(rec)
  })
  .catch(function(e) {
    console.log(e);
  })
```

At this point it will work. Now if you add any index(for example UNIQUE) to Vertex Addresses the above script fails to remove the Address records.

```sql
delete vertex Addresses where  id in $appIds
```
The addresses rows are not deleted. If i execute the queries manually from studio or client it works.

**Comment by maggiolo00** [comment] 2016-08-04 09:56
hi @mindnuts 
thanks for the steps to reproduce it. 
Let me check it.

**Comment by mindnuts** [comment] 2016-08-04 10:04
@maggiolo00 Thanks for the quick response

**Comment by maggiolo00** [comment] 2016-08-10 11:19
@mindnuts 

reproduced. 
Seems to be related to Batch Script

Steps

1) Db Creation

```
CREATE CLASS Addresses extends V
CREATE PROPERTY Addresses.city STRING
CREATE PROPERTY Addresses.id STRING
CREATE PROPERTY Addresses.street STRING

CREATE CLASS Employees extends V
CREATE PROPERTY Employees.email STRING
CREATE PROPERTY Employees.name STRING
CREATE PROPERTY Employees.id STRING

CREATE CLASS belongs_to extends E
INSERT INTO Employees SET name = 'Homer Simpson', email = 'homer@nuclear.com', id = "818bd3cf-6dd4-407b-8290-5f4b4525a5a6"
INSERT INTO Addresses SET city = 'Springfield', street = '54, down lane', id = "80007b02-ca18-4629-af8e-a3ef5a1702f4"
INSERT INTO Addresses SET city = 'rohbach', street = '34, nashbrough', id = "4fee1921-be40-4a8c-be6c-fedf826e414f"
create edge belongs_to from (select from Addresses) to (select from Employees)
```

2) Script With Correct Results

```
BEGIN
 LET appIds = select list(id) from (select expand (in('belongs_to')) from Employees where email = 'homer@nuclear.com' )
 LET appId = select from Addresses where id in $appIds
COMMIT 
```

3) Index Creation

```SQL
create index Addresses.id on Addresses (id) NOTUNIQUE
```

4) Retry step 2.

**Comment by luigidellaquila** [comment] 2016-08-10 12:05
Thanks @maggiolo00 

I'll check it asap

Luigi

**Comment by luigidellaquila** [comment] 2016-08-10 13:01
Hi @mindnuts 

Two problems here:

1. the query 
```
select list(id) from (select expand (in('belongs_to')) from Employees where email = 'homer@nuclear.com' )
```
returns a single record, with an attribute containing the list, eg. `{@rid: #-2:-1, list:[foo, bar]}` so the condition `where id in $appIds` is not supposed to pass (but it does, and I think it's a mistake in the executor)

2. The right query would be
```
select list(id) from (select expand (in('belongs_to')) from Employees where email = 'homer@nuclear.com' )
```
the bad thing is that it doesn't work with indexes as well. But the good thing is that I have a fix for this, I'm running the tests now to see if it solves the problem

Thanks

Luigi

**Comment by mindnuts** [comment] 2016-08-10 13:13
@luigidellaquila Not sure if you posted the "Right" query. Both look same.

**Comment by luigidellaquila** [comment] 2016-08-10 13:14
ops, sorry, the right query is

```
select id from (select expand (in('belongs_to')) from Employees where email = 'homer@nuclear.com' )
```

Thanks

Luigi

**Comment by luigidellaquila** [comment] 2016-08-10 13:17
Ok, I just pushed a fix on 2.2.x, it will be released in short with 2.2.7.

Thanks

Luigi

**Comment by luigidellaquila** [comment] 2016-08-13 07:07
Hi @mindnuts 

The release is available on the website, I'm closing this issue

Thanks

Luigi

**Closed by luigidellaquila** 2016-08-13 07:07 UTC

**Comment by mindnuts** [comment] 2016-08-16 07:34
@luigidellaquila I am not sure where the fix was added. I checked the release notes for the last release 2.2.7 and this issue was not mentioned there.

**Comment by luigidellaquila** [comment] 2016-08-16 08:10
Hi @mindnuts 

this is the commit that fixes the problem

https://github.com/orientechnologies/orientdb/commit/837ae6468d6399f477b015762cc77f730c8ad6da

The commit message is a bit cryptic, but it's the root cause of this bug

Thanks

Luigi
