### ISSUE TITLE
Query that works though ODB Studio fails through OrientJS

### ISSUE THREAD

**Issue by georgiana-b** [orientechnologies/orientjs#304] opened 2018-03-22 09:38 UTC
I have the following query:

```sql
   SELECT actorRID,
   partnerRID,
   set(bidRID) as sharedBidRIDs
   FROM (
     SELECT bidRID,
     actorRID,
     partnerRID,
     set(actorRID, partnerRID) as pair
     FROM (
       SELECT @rid as bidRID,
       in('Awards') as actorRID,
       in('Awards') as partnerRID
       FROM Bid
       WHERE xCountry in ["UK"] AND xYear in [2017] AND out('AppliedTo').in('Comprises').out('HasCPV').code in ["79810000"]
       AND isWinning=true
       AND in('Awards').size() > 1
       UNWIND actorRID, partnerRID
     ) WHERE actorRID != partnerRID
   ) GROUP BY pair;
```

When I execute it through OritentDB studio, it works without problems:
![working-edge-query](https://user-images.githubusercontent.com/8862002/37761673-feb78a8a-2dc2-11e8-8557-9bf2741e5910.png)

But when I execute it from my app through OrientJS, ODB raises the following errors (excerpt from ODB logs):

```
Exception `5E2F8925` in storage `plocal:/orientdb/databases/elvis`: 3.0.0RC2 - Veloce (build f833ecfdbc293875a429e9831d0ff6a467db076d, branch develop)
com.orientechnologies.orient.core.exception.OCommandExecutionException: Error on execution of command: sql.SELECT actorRID,
    partnerRID,
    sharedBidRIDs.size() as value
    FROM (
      SELECT actorRID,
      partnerRID,
      set(bidRID) as sharedBidRIDs
      FROM (
        SELECT bidRID,
        actorRID,
        partnerRID,
        set(actorRID, partnerRID) as pair
        FROM (
          SELECT @rid as bidRID,
          in('Awards') as actorRID,
          in('Awards') as partnerRID
          FROM Bid
          WHERE xCountry in ["UK"] AND xYear in [2017] AND out('AppliedTo').in('Comprises').out('HasCPV').code in ["79810000"]
          AND isWinning=true
          AND in('Awards').size() > 1
          UNWIND actorRID, partnerRID
        ) WHERE actorRID != partnerRID
      ) GROUP BY pair
    )
        DB name="elvis"
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:3634)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:3550)
        at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:68)
        at com.orientechnologies.orient.server.OConnectionBinaryExecutor.executeCommand(OConnectionBinaryExecutor.java:578)
        at com.orientechnologies.orient.client.remote.message.OCommandRequest.execute(OCommandRequest.java:103)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sessionRequest(ONetworkProtocolBinary.java:274)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:179)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:82)
Caused by: java.lang.ClassCastException
3/22/18 8:55:42 AM =============================================================

-- Gauges ----------------------------------------------------------------------
org.apache.tinkerpop.gremlin.server.GremlinServer.gremlin-groovy.sessionless.class-cache.average-load-penalty
             value = 1.4294318075E9
org.apache.tinkerpop.gremlin.server.GremlinServer.gremlin-groovy.sessionless.class-cache.estimated-size
             value = 2
org.apache.tinkerpop.gremlin.server.GremlinServer.gremlin-groovy.sessionless.class-cache.eviction-count
             value = 0
org.apache.tinkerpop.gremlin.server.GremlinServer.gremlin-groovy.sessionless.class-cache.eviction-weight
             value = 0
org.apache.tinkerpop.gremlin.server.GremlinServer.gremlin-groovy.sessionless.class-cache.hit-count
             value = 0
org.apache.tinkerpop.gremlin.server.GremlinServer.gremlin-groovy.sessionless.class-cache.hit-rate
             value = 0.0
org.apache.tinkerpop.gremlin.server.GremlinServer.gremlin-groovy.sessionless.class-cache.load-count
             value = 2
org.apache.tinkerpop.gremlin.server.GremlinServer.gremlin-groovy.sessionless.class-cache.load-failure-count
             value = 0
org.apache.tinkerpop.gremlin.server.GremlinServer.gremlin-groovy.sessionless.class-cache.load-failure-rate
             value = 0.0
org.apache.tinkerpop.gremlin.server.GremlinServer.gremlin-groovy.sessionless.class-cache.load-success-count
             value = 2
org.apache.tinkerpop.gremlin.server.GremlinServer.gremlin-groovy.sessionless.class-cache.long-run-compilation-count
             value = 0
org.apache.tinkerpop.gremlin.server.GremlinServer.gremlin-groovy.sessionless.class-cache.miss-count
             value = 2
org.apache.tinkerpop.gremlin.server.GremlinServer.gremlin-groovy.sessionless.class-cache.miss-rate
             value = 1.0
org.apache.tinkerpop.gremlin.server.GremlinServer.gremlin-groovy.sessionless.class-cache.request-count
             value = 2
org.apache.tinkerpop.gremlin.server.GremlinServer.gremlin-groovy.sessionless.class-cache.total-load-time
             value = 2858863615
org.apache.tinkerpop.gremlin.server.GremlinServer.sessions
             value = 0
```

This is how the error looks in OrientSJ:

```js
{error: { OrientDB.RequestError: Error on execution of command: sql.SELECT actorRID,
         partnerRID,
         set(bidRID) as sharedBidRIDs
         FROM (
           SELECT bidRID,
           actorRID,
           partnerRID,
           set(actorRID, partnerRID) as pair
           FROM (
             SELECT @rid as bidRID,
             in('Awards') as actorRID,
             in('Awards') as partnerRID
             FROM Bid
             WHERE xCountry in ["UK"] AND xYear in [2017] AND out('AppliedTo').in('Comprises').out('HasCPV').code in ["79810000"]
             AND isWinning=true
             AND in('Awards').size() > 1
             UNWIND actorRID, partnerRID
           ) WHERE actorRID != partnerRID
         ) GROUP BY pair;
        DB name="elvis"
       at child.Operation.parseError (/home/g/Documents/elvis-backend-node/node_modules/orientjs/lib/transport/binary/protocol33/operation.js:896:13)
       at child.Operation.consume (/home/g/Documents/elvis-backend-node/node_modules/orientjs/lib/transport/binary/protocol33/operation.js:487:35)
       at Connection.process (/home/g/Documents/elvis-backend-node/node_modules/orientjs/lib/transport/binary/connection.js:423:17)
       at Connection.handleSocketData (/home/g/Documents/elvis-backend-node/node_modules/orientjs/lib/transport/binary/connection.js:314:20)
       at emitOne (events.js:115:13)
       at Socket.emit (events.js:210:7)
       at addChunk (_stream_readable.js:250:12)
       at readableAddChunk (_stream_readable.js:237:11)
       at Socket.Readable.push (_stream_readable.js:195:10)
       at TCP.onread (net.js:586:20)
   From previous event:
       at Connection._sendOp (/home/g/Documents/elvis-backend-node/node_modules/orientjs/lib/transport/binary/connection.js:85:10)
       at Connection.send (/home/g/Documents/elvis-backend-node/node_modules/orientjs/lib/transport/binary/connection.js:69:17)
       at /home/g/Documents/elvis-backend-node/node_modules/orientjs/lib/transport/binary/index.js:291:38
   From previous event:
       at BinaryTransport.send (/home/g/Documents/elvis-backend-node/node_modules/orientjs/lib/transport/binary/index.js:289:12)
       at MockServer.send (/home/g/Documents/elvis-backend-node/node_modules/orientjs/lib/db/odatabase.js:123:25)
       at ODatabase.<anonymous> (/home/g/Documents/elvis-backend-node/node_modules/orientjs/lib/db/db.js:188:26)
       at bound (domain.js:301:14)
       at ODatabase.runBound (domain.js:314:12)
       at runCallback (timers.js:800:20)
       at tryOnImmediate (timers.js:762:5)
       at processImmediate [as _immediateCallback] (timers.js:733:5)
   From previous event:
       at ODatabase.Db.send (/home/g/Documents/elvis-backend-node/node_modules/orientjs/lib/db/db.js:180:6)
       at ODatabase.Db.exec (/home/g/Documents/elvis-backend-node/node_modules/orientjs/lib/db/db.js:288:22)
       at ODatabase.Db.query (/home/g/Documents/elvis-backend-node/node_modules/orientjs/lib/db/db.js:322:15)
       at createPartnersEdges (/home/g/Documents/elvis-backend-node/api/writers/network.js:240:20)
       at Object.createNetwork (/home/g/Documents/elvis-backend-node/api/writers/network.js:43:5)
       at <anonymous>
     name: 'OrientDB.RequestError',
     message: 'Error on execution of command: sql.SELECT actorRID,\n      partnerRID,\n      set(bidRID) as sharedBidRIDs\n      FROM (\n        SELECT bidRID,\n        actorRID,\n        partnerRID,\n        set(actorRID, partnerRID) as pair\n        FROM (\n          SELECT @rid as bidRID,\n          in(\'Awards\') as actorRID,\n          in(\'Awards\') as partnerRID\n          FROM Bid\n          WHERE xCountry in ["UK"] AND xYear in [2017] AND out(\'AppliedTo\').in(\'Comprises\').out(\'HasCPV\').code in ["79810000"]\n          AND isWinning=true\n          AND in(\'Awards\').size() > 1\n          UNWIND actorRID, partnerRID\n        ) WHERE actorRID != partnerRID\n      ) GROUP BY pair;\r\n\tDB name="elvis"',
     data: {},
     previous: [],
     id: 1,
     type: 'com.orientechnologies.orient.core.exception.OCommandExecutionException',
     hasMore: 0 },
  error_info: 'OrientDB.RequestError: Error on execution of command: sql.SELECT actorRID,\n      partnerRID,\n      set(bidRID) as sharedBidRIDs\n      FROM (\n        SELECT bidRID,\n        actorRID,\n        partnerRID,\n        set(actorRID, partnerRID) as pair\n        FROM (\n          SELECT @rid as bidRID,\n          in(\'Awards\') as actorRID,\n          in(\'Awards\') as partnerRID\n          FROM Bid\n          WHERE xCountry in ["UK"] AND xYear in [2017] AND out(\'AppliedTo\').in(\'Comprises\').out(\'HasCPV\').code in ["79810000"]\n          AND isWinning=true\n          AND in(\'Awards\').size() > 1\n          UNWIND actorRID, partnerRID\n        ) WHERE actorRID != partnerRID\n      ) GROUP BY pair;\r\n\tDB name="elvis"' }
```
To make sure it is the exact same query I copy-pasted it from the error logs into OrientDB Studio and it worked.

I'm using:
- `OrientDB 3.0.0RC2`
- `OrientJS 2.2.7`
- `Node v8.0.0`

**Comment by georgiana-b** [comment] 2018-03-22 11:05
I just it a try with `OrientJS 2.2.10` straight from `master` and I had the same problem.

**Comment by maggiolo00** [comment] 2018-04-06 15:18
Hi @georgiana-b 

Studio uses the new parser/executor. I think that is the problem. OrientJS still point to the old one.

I see that it's throwing ` java.lang.ClassCastException`

Do you have a simple dataset to reproduce the problem?

Thanks

**Comment by georgiana-b** [comment] 2018-04-10 09:06
> Do you see the error logged on the Server?

The error from ODB Server  logs is the first stack trace I pasted in the issue:

```
Exception `5E2F8925` in storage `plocal:/orientdb/databases/elvis`: 3.0.0RC2 - Veloce (build f833ecfdbc293875a429e9831d0ff6a467db076d, branch develop)
com.orientechnologies.orient.core.exception.OCommandExecutionException: Error on execution of command: sql.SELECT actorRID,
    partnerRID,
    sharedBidRIDs.size() as value
    FROM (
      SELECT actorRID,
      partnerRID,
      set(bidRID) as sharedBidRIDs
      FROM (
        SELECT bidRID,
        actorRID,
        partnerRID,
        set(actorRID, partnerRID) as pair
        FROM (
          SELECT @rid as bidRID,
          in('Awards') as actorRID,
          in('Awards') as partnerRID
          FROM Bid
          WHERE xCountry in ["UK"] AND xYear in [2017] AND out('AppliedTo').in('Comprises').out('HasCPV').code in ["79810000"]
          AND isWinning=true
          AND in('Awards').size() > 1
          UNWIND actorRID, partnerRID
        ) WHERE actorRID != partnerRID
      ) GROUP BY pair
    )
        DB name="elvis"
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:3634)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:3550)
        at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:68)
        at com.orientechnologies.orient.server.OConnectionBinaryExecutor.executeCommand(OConnectionBinaryExecutor.java:578)
        at com.orientechnologies.orient.client.remote.message.OCommandRequest.execute(OCommandRequest.java:103)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sessionRequest(ONetworkProtocolBinary.java:274)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:179)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:82)
Caused by: java.lang.ClassCastException
3/22/18 8:55:42 AM =============================================================

-- Gauges ----------------------------------------------------------------------
org.apache.tinkerpop.gremlin.server.GremlinServer.gremlin-groovy.sessionless.class-cache.average-load-penalty
             value = 1.4294318075E9
org.apache.tinkerpop.gremlin.server.GremlinServer.gremlin-groovy.sessionless.class-cache.estimated-size
             value = 2
org.apache.tinkerpop.gremlin.server.GremlinServer.gremlin-groovy.sessionless.class-cache.eviction-count
             value = 0
org.apache.tinkerpop.gremlin.server.GremlinServer.gremlin-groovy.sessionless.class-cache.eviction-weight
             value = 0
org.apache.tinkerpop.gremlin.server.GremlinServer.gremlin-groovy.sessionless.class-cache.hit-count
             value = 0
org.apache.tinkerpop.gremlin.server.GremlinServer.gremlin-groovy.sessionless.class-cache.hit-rate
             value = 0.0
org.apache.tinkerpop.gremlin.server.GremlinServer.gremlin-groovy.sessionless.class-cache.load-count
             value = 2
org.apache.tinkerpop.gremlin.server.GremlinServer.gremlin-groovy.sessionless.class-cache.load-failure-count
             value = 0
org.apache.tinkerpop.gremlin.server.GremlinServer.gremlin-groovy.sessionless.class-cache.load-failure-rate
             value = 0.0
org.apache.tinkerpop.gremlin.server.GremlinServer.gremlin-groovy.sessionless.class-cache.load-success-count
             value = 2
org.apache.tinkerpop.gremlin.server.GremlinServer.gremlin-groovy.sessionless.class-cache.long-run-compilation-count
             value = 0
org.apache.tinkerpop.gremlin.server.GremlinServer.gremlin-groovy.sessionless.class-cache.miss-count
             value = 2
org.apache.tinkerpop.gremlin.server.GremlinServer.gremlin-groovy.sessionless.class-cache.miss-rate
             value = 1.0
org.apache.tinkerpop.gremlin.server.GremlinServer.gremlin-groovy.sessionless.class-cache.request-count
             value = 2
org.apache.tinkerpop.gremlin.server.GremlinServer.gremlin-groovy.sessionless.class-cache.total-load-time
             value = 2858863615
org.apache.tinkerpop.gremlin.server.GremlinServer.sessions
             value = 0
```

Or you're referring to another log?

**Comment by georgiana-b** [comment] 2018-04-10 09:28
> Studio uses the new parser/executor. I think that is the problem. OrientJS still point to the old one.

I'd be happily switch to the new parser and see if this issue disappears.
Could you outline how to make the switch?

**Comment by maggiolo00** [comment] 2018-04-10 11:06
hi @georgiana-b 

you cannot switch to the new parser. It should be available in the new version of OrientJS 3.0 with the support of new OrientDB 3.0 protocol. But it will be out in the next months

**Comment by maggiolo00** [comment] 2018-04-10 13:36
@georgiana-b 

do you have a small dataset/ schema that we can use to reproduce?

**Comment by georgiana-b** [comment] 2018-04-10 14:09
Yes, the schema is defined in [migrations](https://github.com/tenders-exposed/elvis-backend-node/tree/master/migrations). Just clone [our project](https://github.com/tenders-exposed/elvis-backend-node) and run `npm run migrate`. 

To populate the database we use the NDJSON files in the  `Digiwhist` table [on opentender.eu](https://opentender.eu/download#digiwhist). We have an import script that can be used like this:

```
node --max-old-space-size=6000 scripts/import_data.js -c 10000 -r 4 path/to/file.ndjson
```

Run `node scripts/import_data.js  -h` for details. 
So if you download and extract the NDJSON for UK and use the import script to insert the data you recreate the database I used to get this error.

**Comment by zufanka** [comment] 2018-04-24 08:14
Hi @maggiolo00 !
FYI: as this is *the* blocker issue that keeps our project from moving to ODB3 (which we really need to do as fast as we can), we are trying our luck on [bountysource](https://www.bountysource.com/issues/56326850-query-that-works-though-odb-studio-fails-through-orientjs)

**Comment by maggiolo00** [comment] 2018-04-24 09:04
Hi @zufanka @georgiana-b 

sorry for the late response let me check on this.

**Comment by maggiolo00** [comment] 2018-04-24 12:13
Hi @zufanka @georgiana-b 

just to understand was this query working on 2.2.x?

Thanks

**Comment by maggiolo00** [comment] 2018-04-24 12:56
Hi @georgiana-b @zufanka 

we were able to reproduce this. Seems that there is a problem with the `!=` operator in this query and the old parser/executor. For a temporary workaround you can use `<>` operator should work.
Meanwhile we will try to the fix for this

**Comment by georgiana-b** [comment] 2018-04-25 15:49
> Seems that there is a problem with the != operator in this query and the old parser/executor. For a temporary workaround you can use <> operator should work.
Meanwhile we will try to the fix for this.

You're right, it works with `<>` instead of `!=`. That's great, thank you!

**Comment by georgiana-b** [comment] 2018-04-26 12:41
Hi @luigidellaquila!

I just gave this a try in `v3.0.1-SNAPSHOT - Veloce (build c9383db365d1dc1f5a1b3475befee016ab2182c7, branch develop)`.

It's peculiar that if I try to execute the original query  with `!=` through OrientJS it works now but from OrientDB Studio I get:

```
java.lang.UnsupportedOperationException: Cannot evaluate xCountry IN ["UK"] on index Bid.xCountry
```

I assume this is a problem with ODB Studio because in the server this error is not logged.

Anyway, just to confirm the fix to `!=`, if I replace the range criteria like this it works in ODB Studio and in OrientJS as well:

```
 SELECT actorRID,
 partnerRID,
 set(bidRID) as sharedBidRIDs
 FROM (
   SELECT bidRID,
   actorRID,
   partnerRID,
   set(actorRID, partnerRID) as pair
   FROM (
     SELECT @rid as bidRID,
     in('Awards') as actorRID,
     in('Awards') as partnerRID
     FROM Bid
     WHERE xCountry='UK' 
     AND xYear=2017
     AND isWinning=true
     AND in('Awards').size() > 1
     UNWIND actorRID, partnerRID
   ) WHERE actorRID != partnerRID
 ) GROUP BY pair;
```

**Comment by luigidellaquila** [comment] 2018-04-26 12:49
Hi @georgiana-b 

Yes, that's a completely different problem that I'm investigating now. I'd say it's a regression we introduced very recently, so it should be easy to fix

Thanks

Luigi

**Comment by georgiana-b** [comment] 2018-04-26 12:57
Then I'd say this is solved. Feel free to close it whenever you're done with it.

If I can assist you with trying out other snapshots let me know.

Thanks a lot!

**Comment by luigidellaquila** [comment] 2018-04-27 07:15
Thank you very much @georgiana-b , I also pushed a fix for the remaining problem, now we can consider this fixed

Thanks!

Luigi

**Comment by georgiana-b** [comment] 2018-05-13 14:46
Hi @luigidellaquila @maggiolo00 !

I'm encountering this issue with another query:

```sql
SELECT name, $name_hl, $score FROM Buyer WHERE SEARCH_CLASS("name:rakovník") = true;
```

When I run this in OrientDB Studio I get this:

![buyer_name_query_odb_studio](https://user-images.githubusercontent.com/8862002/39968387-a470972a-56d4-11e8-92f0-10af559ede67.png)

But when I run it from OrientJS I get:

```
Unhandled rejection OrientDB.RequestError: Error on execution of command: sql.SELECT name, $name_hl, $score FROM Buyer WHERE SEARCH_CLASS("name:rakovník") = true;
        DB name="elvis"
    at child.Operation.parseError (/home/g/Documents/elvis-backend-node/node_modules/orientjs/lib/transport/binary/protocol33/operation.js:905:13)
    at child.Operation.consume (/home/g/Documents/elvis-backend-node/node_modules/orientjs/lib/transport/binary/protocol33/operation.js:496:35)
    at Connection.process (/home/g/Documents/elvis-backend-node/node_modules/orientjs/lib/transport/binary/connection.js:430:17)
    at Connection.handleSocketData (/home/g/Documents/elvis-backend-node/node_modules/orientjs/lib/transport/binary/connection.js:314:20)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:250:12)
    at readableAddChunk (_stream_readable.js:237:11)
    at Socket.Readable.push (_stream_readable.js:195:10)
    at TCP.onread (net.js:586:20)
From previous event:
    at Connection._sendOp (/home/g/Documents/elvis-backend-node/node_modules/orientjs/lib/transport/binary/connection.js:85:10)
    at Connection.send (/home/g/Documents/elvis-backend-node/node_modules/orientjs/lib/transport/binary/connection.js:69:17)
    at /home/g/Documents/elvis-backend-node/node_modules/orientjs/lib/transport/binary/index.js:291:38
From previous event:
    at BinaryTransport.send (/home/g/Documents/elvis-backend-node/node_modules/orientjs/lib/transport/binary/index.js:289:12)
    at MockServer.send (/home/g/Documents/elvis-backend-node/node_modules/orientjs/lib/db/odatabase.js:123:25)
    at ODatabase.<anonymous> (/home/g/Documents/elvis-backend-node/node_modules/orientjs/lib/db/db.js:213:26)
    at bound (domain.js:301:14)
    at ODatabase.runBound (domain.js:314:12)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:
    at ODatabase.Db.send (/home/g/Documents/elvis-backend-node/node_modules/orientjs/lib/db/db.js:205:6)
    at ODatabase.Db.exec (/home/g/Documents/elvis-backend-node/node_modules/orientjs/lib/db/db.js:313:22)
    at ODatabase.Db.query (/home/g/Documents/elvis-backend-node/node_modules/orientjs/lib/db/db.js:347:15)
    at repl:1:11
    at ContextifyScript.Script.runInThisContext (vm.js:44:33)
    at REPLServer.defaultEval (repl.js:239:29)
    at bound (domain.js:301:14)
    at REPLServer.runBound [as eval] (domain.js:314:12)
    at REPLServer.onLine (repl.js:433:10)
    at emitOne (events.js:120:20)
    at REPLServer.emit (events.js:210:7)
    at REPLServer.Interface._onLine (readline.js:278:10)
    at REPLServer.Interface._line (readline.js:625:8)
    at REPLServer.Interface._ttyWrite (readline.js:904:14)
    at REPLServer.self._ttyWrite (repl.js:502:7)
    at ReadStream.onkeypress (readline.js:157:10)
    at emitTwo (events.js:125:13)
    at ReadStream.emit (events.js:213:7)
    at emitKeys (internal/readline.js:417:14)
```

This is the error in OrientDB logs:

```
Exception `4C11B5C8` in storage `plocal:/home/g/Documents/orientdb/distribution/target/orientdb-community-3.0.1-SNAPSHOT.dir/orientdb-community-3.0.1-SNAPSHOT/databases/elvis`: 3.0.1-SNAPSHOT - Veloce (build 5d37c46464b74cdf063b89505be56ea9f23c4afb, branch develop)
com.orientechnologies.orient.core.exception.OCommandExecutionException: Error on execution of command: sql.SELECT name, $name_hl, $score FROM Buyer WHERE SEARCH_CLASS("name:rakovník") = true;
        DB name="elvis"
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:3681)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:3597)
        at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:68)
        at com.orientechnologies.orient.server.OConnectionBinaryExecutor.executeCommand(OConnectionBinaryExecutor.java:578)
        at com.orientechnologies.orient.client.remote.message.OCommandRequest.execute(OCommandRequest.java:103)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sessionRequest(ONetworkProtocolBinary.java:284)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:186)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:82)
Caused by: java.lang.NullPointerException
        at com.orientechnologies.lucene.functions.OLuceneSearchOnClassFunction.searchForIndex(OLuceneSearchOnClassFunction.java:147)
        at com.orientechnologies.lucene.functions.OLuceneSearchOnClassFunction.searchForIndex(OLuceneSearchOnClassFunction.java:143)
        at com.orientechnologies.lucene.functions.OLuceneSearchOnClassFunction.searchFromTarget(OLuceneSearchOnClassFunction.java:112)
        at com.orientechnologies.lucene.functions.OLuceneSearchFunctionTemplate.estimate(OLuceneSearchFunctionTemplate.java:46)
        at com.orientechnologies.orient.core.sql.parser.OFunctionCall.estimateIndexedFunction(OFunctionCall.java:182)
        at com.orientechnologies.orient.core.sql.parser.OLevelZeroIdentifier.estimateIndexedFunction(OLevelZeroIdentifier.java:80)
        at com.orientechnologies.orient.core.sql.parser.OBaseIdentifier.estimateIndexedFunction(OBaseIdentifier.java:87)
        at com.orientechnologies.orient.core.sql.parser.OBaseExpression.estimateIndexedFunction(OBaseExpression.java:149)
        at com.orientechnologies.orient.core.sql.parser.OExpression.estimateIndexedFunction(OExpression.java:288)
        at com.orientechnologies.orient.core.sql.parser.OBinaryCondition.estimateIndexed(OBinaryCondition.java:111)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.tryIndexedFunctions(OCommandExecutorSQLSelect.java:2281)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.searchForIndexes(OCommandExecutorSQLSelect.java:2073)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.searchInClasses(OCommandExecutorSQLSelect.java:991)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLResultsetAbstract.assignTarget(OCommandExecutorSQLResultsetAbstract.java:198)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.assignTarget(OCommandExecutorSQLSelect.java:516)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.executeSearch(OCommandExecutorSQLSelect.java:498)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.execute(OCommandExecutorSQLSelect.java:474)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:74)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:3660)
        ... 7 more
```

I'm using:

`OrientJS 2.2.10`
`OrientDB community-3.0.1-SNAPSHOT`
 `Node 8.0.0`

It's a very different query but the exception is the same so I thought this could be reopen. Let me know if you think it would be better to open another issue.

**Comment by luigidellaquila** [comment] 2018-05-14 06:50
Hi @georgiana-b 

It seems to be a different problem, I'm checking it now, I'll let you know asap

Thanks

Luigi

**Comment by luigidellaquila** [comment] 2018-05-14 08:30
Hi @georgiana-b 

I just pushed a fix and created a new snapshot, could you please check and let me know if it solves the problem?

Thanks

Luigi

**Comment by georgiana-b** [comment] 2018-05-14 08:36
Awesome! I'll give it a try right now.

**Comment by georgiana-b** [comment] 2018-05-14 10:18
@luigidellaquila I just tried it again and I get the same error.

Just to make sure I run the version that contains your fix I'll tell you what I did:

- `git pull origin develop`  and got [your recent commit](https://github.com/orientechnologies/orientdb/commit/57aa1df078911f48f17f576ac1a51b104e1578b)
- `mvn clean install -DskipTests`
- `./distribution/target/orientdb-community-3.0.1-SNAPSHOT.dir/orientdb-community-3.0.1-SNAPSHOT/bin/server.sh`

I think it's the latest because the stats of the core jar show it was updated today

```
stat ./distribution/target/orientdb-community-3.0.1-SNAPSHOT.dir/orientdb-community-3.0.1-SNAPSHOT/lib/orientdb-core-3.0.1-SNAPSHOT.jar
  File: ./distribution/target/orientdb-community-3.0.1-SNAPSHOT.dir/orientdb-community-3.0.1-SNAPSHOT/lib/orientdb-core-3.0.1-SNAPSHOT.jar
  Size: 4833016         Blocks: 9440       IO Block: 4096   regular file
Device: 10305h/66309d   Inode: 16178671    Links: 1
Access: (0644/-rw-r--r--)  Uid: ( 1001/       g)   Gid: (  100/   users)
Access: 2018-05-14 12:57:23.852513853 +0300
Modify: 2018-05-14 12:31:49.680000000 +0300
Change: 2018-05-14 12:35:21.028532145 +0300
```

**Comment by luigidellaquila** [comment] 2018-05-14 10:29
Mmm... yes, the version seems to be correct, let me double-check

Thanks

Luigi

**Comment by luigidellaquila** [comment] 2018-05-14 13:29
Hi @georgiana-b 

I managed to test it on the original database and to replicate the exact problem.
I pushed another fix, now it should be OK

Thanks

Luigi

**Comment by georgiana-b** [comment] 2018-05-14 14:58
@luigidellaquila  Indeed it work now. Well done.

Feel free to close this. 

Much appreciated!

**Comment by luigidellaquila** [comment] 2018-05-14 15:03
Hi @georgiana-b 

Thanks you very much for your feedback!

Closing then, thanks

Luigi

**Closed by luigidellaquila** 2018-05-14 15:03 UTC
Labels: bug
