### ISSUE TITLE
Query result is different results by orientjs API version

### ISSUE THREAD

**Issue by Leeingnyo** [orientechnologies/orientjs#352] opened 2018-12-12 00:42 UTC
I'm moving to OrientJS 3.0 new API now (using OrientDBClient, sessions).
However, I met different results with new API. My model is roughly 

```
class Name {
  ko: String
  hangul: String
  latin: String
}
class Song {
  name: Name
}
```

And here is my query

```
SELECT * FROM Song WHERE "relations" in name.values()
```

with the old API, the result is correct as expected,
but with the new one, no match records...

And I tried `SELECT name.values() FROM Song` on orientdb studio, the output is a list of empty.
I think that it's a bug on OrientDB 3.0.x

**Comment by Leeingnyo** [comment] 2018-12-13 12:54
After some tests, I decided to run the query `SELECT * FROM Song WHERE "relations" in unionall(name.ko, name.hangul, name.latin)` instead.
Is there any other better way?

**Comment by wolf4ood** [comment] 2018-12-13 13:01
Hi @Leeingnyo 

is name a map right?

**Comment by Leeingnyo** [comment] 2018-12-13 13:15
No, It's `EMBEDDED` type. `Name` is Linked Class.

**Comment by Leeingnyo** [comment] 2018-12-13 13:23
I found another way. I can get expected results with a query `SELECT * FROM Song WHERE "relations" in name.asList()`

**Comment by wolf4ood** [comment] 2018-12-20 17:05
Hi @Leeingnyo 

is it working now?

**Comment by wolf4ood** [comment] 2018-12-21 14:00
Hi @Leeingnyo 

i've reproduced and fixed the issue which was in OrientDB as you guessed.
I'm closing this since I've raised an issue on OrientDB project.

Thanks

**Closed as completed by wolf4ood** 2018-12-21 14:00 UTC
Labels: duplicate

**Comment by Leeingnyo** [comment] 2018-12-21 15:34
Hi @wolf4ood 

Thank you for fixing! I'll wait for next version up
