### ISSUE TITLE
v2.2.0 Fatal error : Assertion failed: (next > 0)

### ISSUE THREAD

**Issue by rajeshvaya** [orientechnologies/orientjs#179] opened 2016-05-24 06:17 UTC
# OrientDB Server
v2.2.0

# OrientJS Driver
v2.2.0

# NodeJS
v6.1.0

# OS
Mac OSX (10.9.4)

# Issue

During the initialization of the connection there is a fatal error `Assertion failed: (next > 0), function prepare, file ../lib/native/helpers.cpp, line 22.` and it application crashes

**Comment by maggiolo00** [comment] 2016-05-24 08:18
hi @rajeshvaya 

which OS?

**Comment by rajeshvaya** [comment] 2016-05-24 08:20
@maggiolo00  Mac OSX (10.9.4)

> I will add it in the description too

**Comment by maggiolo00** [comment] 2016-05-24 08:22
i will try on my Mac
in Travis al works fine the build is green
https://travis-ci.org/orientechnologies/orientjs/jobs/131162938

**Comment by maggiolo00** [comment] 2016-05-24 09:26
do you have a script to replicate this?

**Comment by rajeshvaya** [comment] 2016-05-24 10:57
@maggiolo00 

Please below the attached tar - [orientjs_2.2.0.tar.gz](https://github.com/orientechnologies/orientjs/files/279293/orientjs_2.2.0.tar.gz) - which contains the database export and a simple JS script to run against the database (just change the OrientDB server connection details as per your setup)

So after you download, just run the following

```bash
tar -zxvf orientjs_2.2.0.tar.gz
cd orientjs_2.2.0
sudo npm install
# import the database file to OrientDB v2.2.0, then run the following
node index.js
```

The output for the above is 
```Assertion failed: (next > 0), function prepare, file ../lib/native/helpers.cpp, line 22.```

**Comment by maggiolo00** [comment] 2016-05-24 11:02
@rajeshvaya 
thanks

**Comment by rajeshvaya** [comment] 2016-05-25 07:33
@maggiolo00 any update on the possible reason?

**Comment by maggiolo00** [comment] 2016-05-25 08:07
hi @rajeshvaya not yet. It's in my todo list. 
I will work on this tomorrow

**Comment by maggiolo00** [comment] 2016-05-26 11:47
@rajeshvaya 
i've run your test without problem.
I'm on OSX too. 
I will try it out on another Mac

**Comment by rajeshvaya** [comment] 2016-05-26 12:12
@maggiolo00 
I ran my script on a fresh ubuntu vm and I am getting the same error too.

**Comment by rajeshvaya** [comment] 2016-05-26 12:17
@maggiolo00 on ubuntu I get more description of the error

> node: ../lib/native/helpers.cpp:22: void Orient::ContentBuffer::prepare(int): Assertion `next > 0' failed.

**Comment by kiejo** [comment] 2016-06-01 09:23
I get the same error on Ubuntu when trying to update a string field to an empty string. The code looks something like this:
```javascript
db.update('rid').set({title: ''}).one()
```

**Comment by maggiolo00** [comment] 2016-06-01 09:35
@kiejo 
which version  of OrientDB?

**Comment by kiejo** [comment] 2016-06-01 10:37
I tested this using:
OrientDB 2.2.0
OrientJS 2.2.0
Node.js 4.4.2

**Comment by zhengguozhu** [comment] 2016-06-09 15:52
CentOS 7.0 64bit, OrientDB 2.2.0, orientjs 2.2.0, nodejs 4.4.4, same issue while querying embedded field with json string as content.

**Comment by maggiolo00** [comment] 2016-06-09 15:53
@zhengguozhu 
do you have a test case to reproduce it?

**Comment by zhengguozhu** [comment] 2016-06-09 16:07
@maggiolo00 can you try with create a vertex with a property of embedded type, then select it?
It works on CentOS 6.5, but failed on CentOS 7.0.

**Comment by maggiolo00** [comment] 2016-06-09 16:08
@zhengguozhu 
with the same node version?

**Comment by zhengguozhu** [comment] 2016-06-09 16:14
@maggiolo00 yes, same version.

**Comment by zhengguozhu** [comment] 2016-06-09 16:15
also works with OrientDB 2.1.7, just failed with OrientDB 2.2.0.

**Comment by maggiolo00** [comment] 2016-06-09 16:18
yes because it uses the old protocol format. Let me try to reproduce it locally

**Comment by zhengguozhu** [comment] 2016-06-11 13:47
can you reproduce now?

**Comment by mindnuts** [comment] 2016-06-14 09:48
same issue for me. Versions:
Node 4.2.4
Orientdb 2.2.2
OrientJS 2.2.0
Ubuntu 14.04


```bash
node: ../lib/native/helpers.cpp:22: void Orient::ContentBuffer::prepare(int): Assertion `next > 0' failed.
```

Script to reproduce this issue:

```javascript
'use strict';
var OrientDB = require('orientjs');

var server = OrientDB({
  host: '172.17.8.101',
  port: 2424,
  username: 'root',
  password: 'root'
});

var db = server.use('WebDbData');
console.log('Using database: ' + db.name);

db.query("Select * from applications where status = 'Applied' ")
.then(function (applications) {    
  console.log('applications', applications);
  
});
```

**Comment by mindnuts** [comment] 2016-06-14 09:51
@lvca This is a serious issue which is preventing us from using Orientdb 2.2.2. We would like to migrate our server from present 2.1.16 to 2.2.2 to reap benefits from the improved stability and performance gains in 2.2.x version.

**Comment by maggiolo00** [comment] 2016-06-14 10:08
@mindnuts 
i'm working on it now.
Can you describe some of the records returned by that query?

**Comment by maggiolo00** [comment] 2016-06-14 10:15
@mindnuts 

the strange thing is that al the tests travis are ok on the same version as you mention of Ubuntu i think
https://travis-ci.org/orientechnologies/orientjs

**Comment by rajeshvaya** [comment] 2016-06-14 10:18
@maggiolo00 I think the issue is with embedded data and when we query that

**Comment by mindnuts** [comment] 2016-06-14 10:27
@maggiolo00 Here you go
https://gist.github.com/mindnuts/b03ebb40826b6b1fcdcceb98885e0b55

**Comment by maggiolo00** [comment] 2016-06-14 10:43
@mindnuts 
@rajeshvaya 
thanks i've reproduce and working on it

**Comment by maggiolo00** [comment] 2016-06-14 17:13
hi @rajeshvaya 
@mindnuts 
should be fixed in the native serializer. I'm running test now for OrientJs then we will release a package with this fix probably tomorrow

**Comment by maggiolo00** [comment] 2016-06-14 17:20
Just released OrientJS 2.2.1 that should contain the fix
@rajeshvaya 
@mindnuts 
can you confirm that is fixed?

**Comment by mindnuts** [comment] 2016-06-16 10:23
@maggiolo00 I can confirm its working for me

**Closed** 2016-06-16 10:24 UTC
Labels: bug, resolved

**Comment by rajeshvaya** [comment] 2016-06-16 11:10
@maggiolo00 Works for me too, thanks!
