### ISSUE TITLE
node-gyp rebuild error on windows and can not find module 'arrify' on ubuntu

### ISSUE THREAD

**Issue by terrygreen0606** [orientechnologies/orientjs#413] opened 2019-11-29 19:46 UTC
I installed orientjs with npm on windows and ubuntu.

When I execute the file that requires orientjs, it gives node-gyp rebuild error on windows and can not find module 'arrify' on ubuntu.

- On Windows
 I tried hundreds of times with binding.gyp and binding.cc files.

- On Ubuntu
 When I install 'arrify', it gives another error of 'parse-function'.

Could you help me fix these?

These are the error image of ubuntu and windows.

![ubuntu_error](https://user-images.githubusercontent.com/54503006/69888205-9dc6f180-1325-11ea-86af-4959b9c07ca2.png)

![windows_error](https://user-images.githubusercontent.com/54503006/69888207-a15a7880-1325-11ea-86fd-b94c90f6b723.png)

**Comment by jymcheong** [comment] 2019-12-03 05:23
Encountered the same problem. Went into my VM that had a functional version of my software & checked the node_modules directory, I noticed something different.

# Root Cause
Changes in parse-function module broke orientjs 

Working version: `parse-function@5.4.4`

Failed version: `parse-function@5.5.0`

# Resolution

Install `parse-function@5.4.4` 

I tested at my end, works fine now.

![Screenshot 2019-12-03 13 25 44](https://user-images.githubusercontent.com/11232021/70022800-6b8cec80-15d0-11ea-858f-56d56207312f.png)

**Comment by terrygreen0606** [comment] 2019-12-04 13:01
Thank you very much for your help, jymcheong. It's working.

**Comment by terrygreen0606** [comment] 2019-12-04 13:01
Do I have to install arrify, too? I installed that first and then installed parse-function@5.4.4.

**Comment by jymcheong** [comment] 2019-12-05 04:39
> Do I have to install arrify, too? I installed that first and then installed parse-function@5.4.4.

Parse-function@5.4.4 likely does not depend on arrify. It is the newer 5.5.0 that needs it. But the way it is used in orientJS seems to be broken even after installing arrify. So I just roll back to older parse-function since I not sure what to change at orientJS to fix the issue.

**Comment by Nopzen** [comment] 2019-12-06 19:34
I can confirm this issue aswell, @jymcheong 's fix of installing 5.4.4 seems to be working .
But would be nice to be fixed resolved from maintainers :)

**Comment by terrygreen0606** [comment] 2019-12-07 15:55
> > Do I have to install arrify, too? I installed that first and then installed parse-function@5.4.4.
> 
> Parse-function@5.4.4 likely does not depend on arrify. It is the newer 5.5.0 that needs it. But the way it is used in orientJS seems to be broken even after installing arrify. So I just roll back to older parse-function since I not sure what to change at orientJS to fix the issue.

That's right. I removed arrify and installed just parse-function@5.4.4. And it works without any problems. I don't know why it doesn't go on with the new version of parse-function.

I found another way to use the new version of parse-function with orientjs.
Navigate to node_modules/orientjs/lib/db/db.js and then find require('parse-function')().
Here, I removed the last brackets so that it looks like require('parse-function').
This also works. I don't know the reason, but anyhow it works without any problems with the version of 5.4.4.

**Comment by wolf4ood** [comment] 2019-12-11 10:41
Hi Folks

i've merged this PR https://github.com/orientechnologies/orientjs/pull/416

which fixed this. I will publish a new version most likely today

Thanks

**Comment by tglman** [comment] 2023-11-03 13:11
Hi,

Fixed a while ago, closing

**Closed as completed by tglman** 2023-11-03 13:11 UTC
